[project]
org-name = "wso2"
version = "1.1.1"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "pass-through"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["pass_through_messaging"]

[dependencies]
