[project]
org-name = "wso2"
version = "1.1.1"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "service"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["service_composition"]

[dependencies]
