[project]
org-name = "wso2"
version = "1.1.0"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "json", "jms"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["json_to_jms"]

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "json_to_jms"
  path = "./lib/activemq-client-5.15.5.jar"

  [[platform.libraries]]
  module = "json_to_jms"
  path = "./lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar"

  [[platform.libraries]]
  module = "json_to_jms"
  path = "./lib/hawtbuf-1.11.jar"
