[project]
org-name = "wso2"
version = "1.1.2"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "scatter-gather"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["scatter_gather_flow"]

[dependencies]
