[project]
org-name = "wso2"
version = "1.1.2"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "ftp"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["file_integration_using_ftp"]

[dependencies]
