[project]
org-name= "wso2"
version= "0.1.2"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "amazons3"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["integration_with_amazon_s3_bucket"]

[dependencies]
