[project]
org-name = "wso2"
version = "1.2.2"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "data-backed"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["data_backed_service"]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "data_backed_service"
    path = "./lib/mysql-connector-java-8.0.11.jar"
