[project]
org-name= "wso2"
version= "1.0.0"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["protocol_switch_service"]

[dependencies]
