[project]
org-name= "wso2"
version= "1.0.0"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "google", "spreadsheets"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["backup_csv_files_using_gsheets4"]

[dependencies]
