[project]
org-name= "wso2"
version = "1.1.0"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "salesforce", "ftp"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["salesforce_ftp_integration"]

[dependencies]
